/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labarchivosbinarios;

import java.io.IOException;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setSize(470, 480);
        this.setLocationRelativeTo(null);
        menu.setSize(470, 520);
        menu.setVisible(true);
        addEmployee.setSize(470, 520);
        addEmployee.setVisible(false);
        listEmployee.setSize(470, 520);
        listEmployee.setVisible(false);
        addSale.setSize(470, 520);
        addSale.setVisible(false);
        payEmployee.setSize(470, 520);
        payEmployee.setVisible(false);
        despedir.setSize(470, 520);
        despedir.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        botonListar = new javax.swing.JButton();
        botonAgregarVenta = new javax.swing.JButton();
        botonPagarEmpleado = new javax.swing.JButton();
        botonDespedirEmpleado = new javax.swing.JButton();
        payEmployee = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Codigozzz = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        addSale = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Venta = new javax.swing.JTextField();
        AgregarVentaRegresar = new javax.swing.JButton();
        AgregarVentaBoton = new javax.swing.JButton();
        listEmployee = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        printEmployees = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        addEmployee = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        RegresarAgregarEmpleado = new javax.swing.JButton();
        AgregarEmpledoBoton = new javax.swing.JButton();
        despedir = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(255, 255, 204));
        menu.setPreferredSize(new java.awt.Dimension(470, 440));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("Menu Principal");
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 260, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 51));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 260, 30));

        botonAgregar.setBackground(new java.awt.Color(255, 255, 0));
        botonAgregar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(153, 153, 0));
        botonAgregar.setText("Agregar Empleado");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        menu.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 260, 30));

        botonListar.setBackground(new java.awt.Color(255, 255, 0));
        botonListar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        botonListar.setForeground(new java.awt.Color(153, 153, 0));
        botonListar.setText("Listar Empleados No Despedidos");
        botonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarActionPerformed(evt);
            }
        });
        menu.add(botonListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 310, 30));

        botonAgregarVenta.setBackground(new java.awt.Color(255, 255, 0));
        botonAgregarVenta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        botonAgregarVenta.setForeground(new java.awt.Color(153, 153, 0));
        botonAgregarVenta.setText("Agregar Venta a Empleado");
        botonAgregarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarVentaActionPerformed(evt);
            }
        });
        menu.add(botonAgregarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 260, 30));

        botonPagarEmpleado.setBackground(new java.awt.Color(255, 255, 0));
        botonPagarEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        botonPagarEmpleado.setForeground(new java.awt.Color(153, 153, 0));
        botonPagarEmpleado.setText("Pagar Empleado");
        botonPagarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarEmpleadoActionPerformed(evt);
            }
        });
        menu.add(botonPagarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 260, 30));

        botonDespedirEmpleado.setBackground(new java.awt.Color(255, 255, 0));
        botonDespedirEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        botonDespedirEmpleado.setForeground(new java.awt.Color(153, 153, 0));
        botonDespedirEmpleado.setText("Despedir Empleado");
        botonDespedirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDespedirEmpleadoActionPerformed(evt);
            }
        });
        menu.add(botonDespedirEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 260, 30));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 480));

        payEmployee.setBackground(new java.awt.Color(255, 255, 204));
        payEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 0));
        jLabel9.setText("Pagar Empleado");
        payEmployee.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 360, 70));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 0));
        jLabel11.setText("Codigo");
        payEmployee.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 130, 60));

        Codigozzz.setBackground(new java.awt.Color(255, 255, 255));
        Codigozzz.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        Codigozzz.setForeground(new java.awt.Color(0, 0, 0));
        payEmployee.add(Codigozzz, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 220, 40));

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        payEmployee.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 180, 70));

        jButton4.setBackground(new java.awt.Color(102, 102, 0));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 0));
        jButton4.setText("Pagar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        payEmployee.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 170, 70));

        getContentPane().add(payEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 440));

        addSale.setBackground(new java.awt.Color(255, 255, 204));
        addSale.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 0));
        jLabel6.setText("Agregar Venta");
        addSale.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 0));
        jLabel7.setText("Codigo");
        addSale.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, 50));

        Codigo.setBackground(new java.awt.Color(255, 255, 255));
        Codigo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        Codigo.setForeground(new java.awt.Color(0, 0, 0));
        addSale.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 200, 30));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 0));
        jLabel8.setText("Ventas");
        addSale.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 90, 50));

        Venta.setBackground(new java.awt.Color(255, 255, 255));
        Venta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        Venta.setForeground(new java.awt.Color(0, 0, 0));
        addSale.add(Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, 30));

        AgregarVentaRegresar.setBackground(new java.awt.Color(102, 0, 0));
        AgregarVentaRegresar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        AgregarVentaRegresar.setForeground(new java.awt.Color(255, 0, 0));
        AgregarVentaRegresar.setText("Regresar");
        AgregarVentaRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVentaRegresarActionPerformed(evt);
            }
        });
        addSale.add(AgregarVentaRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 180, 60));

        AgregarVentaBoton.setBackground(new java.awt.Color(102, 102, 0));
        AgregarVentaBoton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        AgregarVentaBoton.setForeground(new java.awt.Color(255, 255, 0));
        AgregarVentaBoton.setText("Agregar");
        AgregarVentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVentaBotonActionPerformed(evt);
            }
        });
        addSale.add(AgregarVentaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 170, 60));

        getContentPane().add(addSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 450));

        listEmployee.setBackground(new java.awt.Color(255, 255, 204));
        listEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 0));
        jLabel5.setText("Listar Empleados");
        listEmployee.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 300, 70));

        printEmployees.setBackground(new java.awt.Color(255, 255, 204));
        printEmployees.setColumns(20);
        printEmployees.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        printEmployees.setForeground(new java.awt.Color(0, 0, 0));
        printEmployees.setRows(5);
        printEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(printEmployees);

        listEmployee.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, 300));

        jButton2.setBackground(new java.awt.Color(153, 153, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        listEmployee.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 200, 40));

        getContentPane().add(listEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 480));

        addEmployee.setBackground(new java.awt.Color(255, 255, 204));
        addEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("Salario");
        addEmployee.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 60, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("Agregar Empleado");
        addEmployee.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 310, 60));

        salary.setBackground(new java.awt.Color(255, 255, 255));
        salary.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        salary.setForeground(new java.awt.Color(0, 0, 0));
        addEmployee.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 240, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 0));
        jLabel4.setText("Agregar Empleado");
        addEmployee.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 60));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        addEmployee.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 240, 30));

        RegresarAgregarEmpleado.setBackground(new java.awt.Color(102, 0, 0));
        RegresarAgregarEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        RegresarAgregarEmpleado.setForeground(new java.awt.Color(255, 0, 0));
        RegresarAgregarEmpleado.setText("Regresar");
        RegresarAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarAgregarEmpleadoActionPerformed(evt);
            }
        });
        addEmployee.add(RegresarAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 160, 60));

        AgregarEmpledoBoton.setBackground(new java.awt.Color(153, 153, 0));
        AgregarEmpledoBoton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        AgregarEmpledoBoton.setForeground(new java.awt.Color(255, 255, 0));
        AgregarEmpledoBoton.setText("Agregar");
        AgregarEmpledoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEmpledoBotonActionPerformed(evt);
            }
        });
        addEmployee.add(AgregarEmpledoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 150, 60));

        getContentPane().add(addEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 440));

        despedir.setBackground(new java.awt.Color(255, 255, 204));
        despedir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 0));
        jLabel10.setText("Codigo");
        despedir.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 60));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 0));
        jLabel12.setText("Despedir Empleado");
        despedir.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 430, 60));

        code.setBackground(new java.awt.Color(255, 255, 255));
        code.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        code.setForeground(new java.awt.Color(0, 0, 0));
        despedir.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 250, 40));

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        despedir.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 200, 70));

        jButton6.setBackground(new java.awt.Color(102, 102, 0));
        jButton6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 0));
        jButton6.setText("Despedir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        despedir.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 200, 70));

        getContentPane().add(despedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    empleadoManager em = new empleadoManager();
    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        menu.setVisible(false);
        addEmployee.setVisible(true);
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void RegresarAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarAgregarEmpleadoActionPerformed
        name.setText("");
        salary.setText("");
        addEmployee.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_RegresarAgregarEmpleadoActionPerformed

    private void AgregarEmpledoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEmpledoBotonActionPerformed
        if(name.getText().isEmpty() || salary.getText().isEmpty()){
           JOptionPane.showMessageDialog(this,"Favor rellenar todas las casillas!");
        }else{
            String Name=name.getText();
            
            try{
                double Salary=Double.parseDouble(salary.getText()); 
                em.addEmployee(Name,Salary);
                JOptionPane.showMessageDialog(null, "Se ha agregado empleado correctamente!");
                name.setText("");
                salary.setText("");
                addEmployee.setVisible(false);
                menu.setVisible(true);
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, "Algo salio mal #.#");
            }catch(InputMismatchException | NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Recuerde Ingresar un valor numerico Oo_oO");
            }
            
        }
    }//GEN-LAST:event_AgregarEmpledoBotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarActionPerformed
        menu.setVisible(false);
        listEmployee.setVisible(true);
        String datos="";
        try{
            em.employeeList();
        }catch(IOException e) {
            JOptionPane.showMessageDialog(null, "Algo salio mal #.#");
        }
        
        for(String emp:empleadoManager.array){ 
            datos+=emp;
        }
        printEmployees.setText(datos);
    }//GEN-LAST:event_botonListarActionPerformed

    private void printEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printEmployeesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_printEmployeesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        printEmployees.setText("");
        listEmployee.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AgregarVentaRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVentaRegresarActionPerformed
        Codigo.setText("");
        Venta.setText("");
        addSale.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_AgregarVentaRegresarActionPerformed

    private void botonAgregarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarVentaActionPerformed
        menu.setVisible(false);
        addSale.setVisible(true);
    }//GEN-LAST:event_botonAgregarVentaActionPerformed

    private void AgregarVentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVentaBotonActionPerformed
        if (Codigo.getText().isEmpty() || Venta.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor rellenar todas las casillas!");
        }else{
            try{
                int codigo=Integer.valueOf(Codigo.getText());
                double venta=Double.valueOf(Venta.getText());
                em.addSalesToEmployee(codigo, venta);   
                
                Codigo.setText("");
                Venta.setText("");
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, "Algo salio mal #.#");
            }catch(InputMismatchException | NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Recuerde Ingresar un valor numerico Oo_oO");
            }
        }
    }//GEN-LAST:event_AgregarVentaBotonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(Codigozzz.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor rellenar todas las casillas!");
        }else{
            try{
                int codigo=Integer.valueOf(Codigozzz.getText());
                em.payEmployee(codigo);
     
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, "Algo salio mal #.#");
            }
            catch(InputMismatchException | NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Recuerde Ingresar un valor numerico Oo_oO");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        payEmployee.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonPagarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarEmpleadoActionPerformed
        menu.setVisible(false);
        payEmployee.setVisible(true);
    }//GEN-LAST:event_botonPagarEmpleadoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        despedir.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(code.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor rellenar todas las casillas!");
        }else{
            try{
                int codigo=Integer.valueOf(code.getText());
                em.fireEmployee(codigo);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Algo salio mal #.#");
            }catch(InputMismatchException | NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Recuerde Ingresar un valor numerico Oo_oO");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void botonDespedirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDespedirEmpleadoActionPerformed
        menu.setVisible(false);
        despedir.setVisible(true);
    }//GEN-LAST:event_botonDespedirEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarEmpledoBoton;
    private javax.swing.JButton AgregarVentaBoton;
    private javax.swing.JButton AgregarVentaRegresar;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField Codigozzz;
    private javax.swing.JButton RegresarAgregarEmpleado;
    private javax.swing.JTextField Venta;
    private javax.swing.JPanel addEmployee;
    private javax.swing.JPanel addSale;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAgregarVenta;
    private javax.swing.JButton botonDespedirEmpleado;
    private javax.swing.JButton botonListar;
    private javax.swing.JButton botonPagarEmpleado;
    private javax.swing.JTextField code;
    private javax.swing.JPanel despedir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listEmployee;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField name;
    private javax.swing.JPanel payEmployee;
    private javax.swing.JTextArea printEmployees;
    private javax.swing.JTextField salary;
    // End of variables declaration//GEN-END:variables
}
